### ISSUE TITLE
When autoscaler scales down(in) an app, does it happen gracefully? What happens to the inflight requests?

### ISSUE THREAD

**Issue by ganeshvaithi** [cloudfoundry/app-autoscaler#570]
We are seeing exceptions like on our springboot app and wonder if the signal to kill the container is not graceful. 

I also see " Exit status 143" indicating it is not a normal exit. So are the inflight requests expected to have issues while scaling down?

["Exception thrown from ApplicationListener handling ContextClosedEvent"],"stck":[["java.lang.NullPointerException","at java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1106)","at java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1097)","at org.apache.cxf.transport.http.DestinationRegistryImpl.removeDestination(DestinationRegistryImpl.java:67)","at org.apache.cxf.transport.http.AbstractHTTPDestination.deactivate(AbstractHTTPDestination.java:976)","at org.apache.cxf.transport.AbstractObservable.setMessageObserver(AbstractObservable.java:65)","at org.apache.cxf.endpoint.ServerImpl.stop(ServerImpl.java:179)","at org.apache.cxf.endpoint.ServerImpl.destroy(ServerImpl.java:185)","at org.apache.cxf.bus.managers.ServerRegistryImpl.preShutdown(ServerRegistryImpl.java:88)","at org.apache.cxf.bus.managers.CXFBusLifeCycleManager.preShutdown(CXFBusLifeCycleManager.java:97)","at org.apache.cxf.bus.extension.ExtensionManagerBus.shutdown(ExtensionManagerBus.java:295)","at org.apache.cxf.bus.extension.ExtensionManagerBus.shutdown(ExtensionManagerBus.java:282)","at org.apache.cxf.bus.spring.SpringBus.onApplicationEvent(SpringBus.java:109)","at org.apache.cxf.bus.spring.SpringBus$1.onApplicationEvent(SpringBus.java:58)","at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)","at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)","at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)","at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)","at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)","at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:992)","at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:929)"]]}

**Comment by silvestre** [comment]
Hi @ganeshvaithi, the App Autoscaler in the end triggers a `cf scale -i <number of app instances>` via the REST API of the Cloud Controller. This means that https://docs.cloudfoundry.org/devguide/deploy-apps/app-lifecycle.html#shutdown applies, and documents the behaviour. The App Autoscaler also does not have a way to influence the behaviour of the platform in this regard.
